### ISSUE TITLE
Feature: Show Indexation Status

### ISSUE THREAD

**Issue by bb** [meilisearch/mini-dashboard#103]
As the Mini-Dashboard may serve as kind of an Admin-UI, it would be great if there was some information on the index updates.

I'm thinking of
* the time of the last successfully processed update
* the number of failed updates since then, if any (and maybe also the time)
* the number of enqueued updates since the last processed, if any (and maybe also the time of the first/last unprocessed enqueued

If this was shown all the time, I think it is hard to decide when to update that and it might spoil the clean design. So maybe it could be in a modal like the API key. Whenever the modal is opened via the "Status" button, show update status (and maybe other stats as well) and never update it, except when modal is closed and opened again. (Later, there might be a refresh button and a time selector after how many seconds to update, etc... but first, the minimal feature set would be great).

**Comment by bidoubiwa** [comment]
Hey @bb! We are currently not adding new features to the mini-dashboard as per [the notice on the readme](https://github.com/meilisearch/mini-dashboard#mini-dashboard). I'm closing this for now. feel free to re-open it if the situation changes.
