### ISSUE TITLE
Link detection too greedy

### ISSUE THREAD

**Issue by bb** [meilisearch/mini-dashboard#126]
The link detection in the FieldValue component is too greedy. The regular expression in https://github.com/meilisearch/mini-dashboard/blob/a71bf046af9f3e5f8007e453cb58b4074b6eb8e6/src/components/Results/Hit.js#L103 should at least have a `^` before https and maybe also check if there are only URL-Characters until the end. Out of my head, a naive approach might be `match(/^https?:\/\/[^\s]+$/)`.

Example document:

```json
[{
  "id": 1,
  "description": "When I need a fast search engine, I go to https://www.meilisearch.com/"
},
{
  "id": 2,
  "description": "https://www.meilisearch.com/ is the place to go when you need instant search."
}]
```

## Actual

Both documents have their description field currently rendered as a full link, i.e.

```html
<a href="When I need a fast search engine, I go to https://www.meilisearch.com/"
   target="_blank" rel="noreferrer" class="sc-pNWdM kMtlSK sc-iklJeh fNZzln">
  <span class="sc-gtsrHT kSJQSN">
    <span>When I need a</span>
    <mark>fast search engine</mark>
    <span> .... 
```

## Expected

I expect the description of neither of the example documents to be rendered as a link.
Rendering a link inside is fine, but not the whole field.

**Comment by gmourier** [comment]
Thanks, Benjamin for this feedback. Indeed, we put the field value in a Link component. This Link component must only surround the link identified by the pattern. 🤓
