### ISSUE TITLE
Slowness during the display

### ISSUE THREAD

**Issue by curquiza** [meilisearch/mini-dashboard#167]
As it was reported [on our Slack community](https://meilicommunity.slack.com/archives/CP9DVS1RQ/p1635176781017400), some slowness is noticeable using the mini-dashboard.

This slowness is not present when only using instant-meilisearch (the dependency used by this repo).
As you can see:

Mini-dashboard:
https://user-images.githubusercontent.com/20380692/139108096-d4e8d7fc-03f8-4157-adc6-11697c02f239.mp4

Only instant-meilisearch
https://user-images.githubusercontent.com/20380692/139108334-2cd7f9fd-a200-46a2-a618-ced5a453a086.mp4

Also here are the processing time of Instant MeiliSearch

<img width="1202" alt="Screenshot 2021-10-26 at 20 43 20" src="https://user-images.githubusercontent.com/20380692/139108810-7fe321cd-e69c-428f-abc1-6025c4d94c91.png">

Can interest @bidoubiwa 
Ask for @bidoubiwa for the dataset

**Comment by curquiza** [comment]
Checked with @bidoubiwa, some additional information that might interest the mini-dashboard:
- we are aware of some latencies (or feeling of latency) on the Instant-MeiliSearch side. We already know how to improve them, here are: https://github.com/meilisearch/instant-meilisearch/issues/588 and https://github.com/meilisearch/instant-meilisearch/issues/569. Once they are fixed, this might help the mini-dashboard being faster! Should be done by @bidoubiwa after the strapi work!
- MeiliSearch is slower since v0.21.0 for some intensive searches because of the `words` criterion that gathers more candidates for each request. Ex: for the "coco titi" query, MeiliSearch now returns all candidates containing "coco" AND "titi" but also just "coco". Before v0.21.0 MeiliSearch only returns candidates containing "coco" AND "titi". This feature was widely asked, that's why it was added, but core team plans to add an option allowing the users to remove this behavior (beginning of 2022 probably). We'll let you know when it's released since it can interest the mini-dashboard.

However, these both points do not explain why there is a difference in latency between instant-meilisearch alone and the mini dashboard, unfortunately (cf videos in the issue description)

**Comment by entrptaher** [comment]
In my mini dashboard, just loading the index list causes the whole page to slow down. It's to be noted I have 1300 indexes as part of the experiment. Each index can have as much as 1000-150k documents, which is noticable in the screenshot. Some of the indexes have 0 documents.

![image](https://user-images.githubusercontent.com/8284972/192828411-15d67548-9726-4a7f-a172-7535e0137a1b.png)

**Comment by bidoubiwa** [comment]
Hey @entrptaher, I see a `search` request that has been done in the calls. How long do the `stats` and the `search` requests take?  This would let us now which one of the routes are being stressed in your setup :)

**Comment by gmourier** [comment]
Hey @bidoubiwa 👋

Using the `GET /indexes` route could help since it's can be paginated with `offset`/ `limit` since v0.28

**Comment by bidoubiwa** [comment]
I agree @gmourier ! I was wondering out of curiosity if it was stats that is causing slowness but we should definitely use `GET /indexes`. @mdubus what do you think?

**Comment by entrptaher** [comment]
The requests are fast, but when they render 1300 items, it gets slow. :(

**Comment by bidoubiwa** [comment]
I think the solution to that would be to lazyload the index list [See example](https://codesandbox.io/s/m726ovzz6y?file=/TestSelect.js:0-100) and more information [here](https://blog.saeloun.com/2022/03/03/infinite-scroll-with-pagination.html)

**Comment by vaibhav135** [comment]
I would like to do this.

**Comment by vaibhav135** [comment]
@bidoubiwa a quick update on this one. I am almost done with it. I am using react-window with react-select. Just need to do little style change and I will be done. Btw I want to know if testing it with 1300 (datasets)  is enough or I should go for more.

**Comment by bidoubiwa** [comment]
Hey @vaibhav135 

Since this PR is very old, I'm not sure this is still an issue. In your PR, could you see a big difference in processing time?

**Comment by vaibhav135** [comment]
Yes definitely, I would say when you have like 1300 (approx.) datasets loaded. The current dropdown is barely usable and super slow. I will attach the before and after once I am done.

**Comment by bidoubiwa** [comment]
Nice! Thanks a lot :) If you already see some significant improvements, you don't need to test with more. If you still would like to, you can use this one https://github.com/meilisearch/datasets/tree/main/datasets/movies

**Comment by vaibhav135** [comment]
Hey, here's a quick before and after

Before
https://github.com/meilisearch/mini-dashboard/assets/39329182/acd1bc10-9fcd-4c3f-b221-c9c711562f1d

After
https://github.com/meilisearch/mini-dashboard/assets/39329182/1aa2f611-ab2a-4f07-8752-16a86401d359

**Comment by bidoubiwa** [comment]
Hey @vaibhav135 thanks, indeed it's way faster :)
