### ISSUE TITLE
[v0.24.0] Rename `errorCode` to `code`

### ISSUE THREAD

**Issue by mdubus** [meilisearch/mini-dashboard#170]
See https://github.com/meilisearch/integration-guides/issues/149

**Comment by curquiza** [comment]
Regarding: https://github.com/meilisearch/MeiliSearch/issues/1898

This should be done before the v0.24.0 release otherwise the users cannot use the mini dashboard in v0.24.0

**Comment by curquiza** [comment]
Discussed with @bidoubiwa and @mdubus -> a tag in `meilisearch-js` will be created for the mini-dashboard with a fresh new version of meilisearch-js containing the needed changes
