### ISSUE TITLE
Style InstantSearch's components instead of using `connect-[component]`

### ISSUE THREAD

**Issue by mdubus** [meilisearch/mini-dashboard#192]
As much as possible, we should try to style directly the InstantSearch's component, intead of using the `connect` functions.
 
Example : 

```js
const Highlight = connectHighlight(
  ({ highlight, attribute, hit, indexContextValue, ...props }) => {
    const parsedHit = highlight({
      highlightProperty: '_highlightResult',
      attribute,
      hit,
    })

    return (
        ...
    )
  }
)
```

This could result in the dashboard being a little faster than it currently is.

**Comment by bidoubiwa** [comment]
We are currently not adding new features to the mini-dashboard as per [the notice on the readme](https://github.com/meilisearch/mini-dashboard#mini-dashboard). I'm closing this for now. feel free to re-open it if the situation changes.
