### ISSUE TITLE
Fields with "." are not displayed correctly

### ISSUE THREAD

**Issue by Nextra** [meilisearch/mini-dashboard#194]
If a field contains "." anywhere in the name, dashboard does not render the field value.

**Comment by mdubus** [comment]
Thanks a lot for your bug report @Nextra !

**Comment by mdubus** [comment]
Hello @Nextra  ! 

After further investigation, it appears that it is not a bug and that documents attributes shouldn't contain dots.
This repository is using [Instant MeiliSearch](https://github.com/meilisearch/instant-meilisearch), which is based on Algolia's [Instant Search](https://www.algolia.com/doc/guides/building-search-ui/what-is-instantsearch/js/) library. 
I invite you to read [this page](https://www.algolia.com/doc/guides/sending-and-managing-data/prepare-your-data/how-to/creating-and-using-nested-attributes/) regarding nested attributes, and adapt your documents according to it.

Don't hesitate if you have any question 😀

**Comment by Nextra** [comment]
Okay, I wasn't aware of compatibility with Algolia in this specific way. Unfortunately MeiliSearch does not yet support configuring nested fields for filtering, which is why I pre-flattened documents in the first place.

Thanks for investigating.
