### ISSUE TITLE
New logo makes text underneath hard to center

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/mini-dashboard#232]
It is centered but it doesnt look centered: 

<img width="319" alt="Screenshot 2022-01-26 at 19 17 13" src="https://user-images.githubusercontent.com/33010418/151222879-972a5038-7f04-45d2-b212-19560a104f13.png">
<img width="826" alt="Screenshot 2022-01-26 at 19 19 05" src="https://user-images.githubusercontent.com/33010418/151222940-fd05ec5b-d005-4614-bb7f-bfd6c4493ecf.png">

**Comment by esmaeilmirzaee** [comment]
May I work on this?

**Comment by bidoubiwa** [comment]
The solution would be to move the version to the right of the logo @esmaeilmirzaee . Is this something you are up for? I made the changes but @mdubus is the official maintainer. Unfortunately she is on holiday, so if the code is a bit off, sorry for that :')

**Comment by lpinot** [comment]
Hey @bidoubiwa :) You can use this logo instead: I added a small margin on the left of the logo, it's gonna look centered now!
![logo_spacing](https://user-images.githubusercontent.com/83015630/151941359-bc050c9c-624b-4314-b683-60e394f9d154.svg)

**Comment by curquiza** [comment]
Thanks @lpinot for the logo

@esmaeilmirzaee you can do the PR to update the logo if you agree. 

In any case, as @bidoubiwa explained, we will wait for @mdubus to come back to accept any merge of PR
