### ISSUE TITLE
Unable to set the master key

### ISSUE THREAD

**Issue by binarweb** [meilisearch/mini-dashboard#257]
**Description**
My server is in production mode and I'm unable to browse the index because there is no way to enter the master key in frontend (I'm assuming that is the way of doing it).

Is there another way of setting up the master key?

**Expected behavior**
Ability to set the master key.

**Current behavior**
As stated in description.

**Screenshots or Logs**

Fresh installation of mini-dashboard shows this:
![image](https://user-images.githubusercontent.com/38425768/161252325-69a80553-bdf5-4605-bedf-dc072cdcf3fa.png)

**Environment:**
- Meilisearch version: [v.0.26.1]
- Browser: [Firefox version 98.0.2]

**Comment by mdubus** [comment]
Hi @binarweb 👋

The front-end makes a call to Meilisearch and displays a modal asking for an API if it is mandatory. 
Can you check that you have configured an API key in your Meilisearch instance? 

You can also try to access your data with this interface by setting your API key in the localStorage, by providing the `apiKey` directly.

Please let me know if any of this resolved your problem. If not, can you upload a screen of your console to see if there's any error? Thanks a lot! 🙏

**Comment by ElectronicaXAB3** [comment]
The Meilisearch instance was running, but it wasn't public. I changed it and it worked.

It should probably say that the Meilisearch server is not running.

Thanks for the help!

**Comment by binarweb** [comment]
The Meilisearch instance was running, but it wasn't public. I changed it and it worked.

It should probably say that the Meilisearch server is not running.

Thanks for the help!

**Comment by mdubus** [comment]
Actually that's weird because we do check if Meilisearch is running, and display a specific message if it's not the case: 
<img width="1488" alt="Capture d’écran 2022-04-07 à 10 33 25" src="https://user-images.githubusercontent.com/30866152/162156814-b456fae6-ce7b-4143-af9f-05934a86ee67.png">

Anyway, I'm glad it's working now 🎉

**Comment by binarweb** [comment]
If you press the "Api Key" button, you will get my screenshot.

I know that it say right there that the Meilisearch instance isn't running, but I thought (before looking into the source code) that the mini-dashboard is proxying Meilisearch. That way, it would not need a public facing interface.
