### ISSUE TITLE
Can we disable mini dashboard website?

### ISSUE THREAD

**Issue by diazsasak** [meilisearch/mini-dashboard#269]
Hi maintainer, we have a meilisearch mini dashboard up and running on our subdomain. We don't want to access it from browser, we only need to access it from postman. can we disable the web but still use it as API?

Thank you..

**Comment by mdubus** [comment]
Hello @diazsasak !

Looks like you are searching for the `production` mode. 
This will disable the mini-dashboard, but still allow you to use the Meilisearch API.

To do so, you can run your Meilisearch instance with the `--env production` flag. But keep in mind that in production mode a [masterKey](https://docs.meilisearch.com/learn/security/master_api_keys.html#master-key-and-api-keys) will be mandatory 😉

Hope this helps!

**Comment by diazsasak** [comment]
Hi @mdubus , 

i see. i will check my environment. thank you!
