### ISSUE TITLE
Support file:/// link in dashboard for click

### ISSUE THREAD

**Issue by gmourier** [meilisearch/mini-dashboard#272]
### Discussed in https://github.com/meilisearch/product/discussions/466

<div type='discussions-op-text'>

<sup>Originally posted by **jet10000** May  3, 2022</sup>
Support click file:/// open like url

file:///Users/mac/github/mlsearch/jpg/34.jpg

</div>

**Comment by vaibhav135** [comment]
@mdubus I am not able to get a full picture of this. Can you give me some more reference to this please or more example.

**Comment by bidoubiwa** [comment]
We are currently not adding new features to the mini-dashboard as per [the notice on the readme](https://github.com/meilisearch/mini-dashboard#mini-dashboard). I'm closing this for now. feel free to re-open it if the situation changes.
