### ISSUE TITLE
Add Facet count and filtering

### ISSUE THREAD

**Issue by bb** [meilisearch/mini-dashboard#28]
It's great to have a better generic backend than the one which is included. I'd really like when this frontend would allow to use more of Meilisearch's included features:

* show facets and facet values (including counts)
* allow filtering based on facet values
* show if facet counts are exhaustive or not
* (later) use patterns to detect e.g. hierarchical facets and show them in a hierarchy

**Comment by bidoubiwa** [comment]
Hey @bb! We are currently not adding new features to the mini-dashboard as per [the notice on the readme](https://github.com/meilisearch/mini-dashboard#mini-dashboard). I'm closing this for now. feel free to re-open it if the situation changes.
