### ISSUE TITLE
Accessibility: make pressing the "enter" key, validate the admin key modal

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/mini-dashboard#280]
When providing the admin key in the modal
<img width="993" alt="Screenshot 2022-07-05 at 12 26 52" src="https://user-images.githubusercontent.com/33010418/177308192-e2814d0a-e92d-413d-9ed2-f44f2afebffa.png">

Pressing on the `enter` key does not validate the input.

For accessibility purposes we should maybe trigger the `ok` when pressing on `enter`

Browser: Chrome Version 103.0.5060.53 (Official Build) (arm64)

**Comment by nooras** [comment]
Hi
I wanted to try this issue.
Can you please assign it to me? 

Thanks

**Comment by bidoubiwa** [comment]
Thanks for your interest in this project 🔥 You are definitely more than welcome to open a PR for this!

We prefer not assigning people to our issues because sometimes people ask to be assigned and never come back, which discourages the real volunteers contributors from opening a PR to fix this issue.
We will accept and merge the first PR that fixes correctly and well implements the issue following our [contributing guidelines](../blob/main/README.md). 

We are looking forward to reviewing your PR 😊
