### ISSUE TITLE
Allow (de-)selecting and reordering fields in fancy view

### ISSUE THREAD

**Issue by bb** [meilisearch/mini-dashboard#29]
If there are maaaany fields in the index but for a quick research I'm just interested in a few, I'd like to select only a subset of the available ones to be shown in the view.

Also, it would be great to be able to reorder the shown fields, e.g. I'd want "title" before "description".

An extended version could later also add something like "transformers":
The default would be "auto" (or maybe "plain").
Then, I'd like to select (from a fixed/hard coded list): e.g. "h1", "h2", to make a field show up as headline.

Other candidates for transformers might be "markdown", "make-links-clickable" or even "embed-as-iframe". Of course, one might go even further but that's most likely out of scope for this project.

**Comment by gmourier** [comment]
Thank you @bb ! Indeed it would be great. We could easily use the index stats endpoint to retrieve the indexed fields and make a selector to choose what to display for a first iteration.

**Comment by vaibhav135** [comment]
I would like to do this. But I am not sure about the design. How would the subset selector look like? Similarly how would the reordering component will look like? 
Are both of them going to be like a modal ? 
Also for reordering are we going to do like a drag and adjust kind of thing?

**Comment by bb** [comment]
@vaibhav135 Feel free to do it in any way you like and present it here to get feedback. The conceptual work is a big part, so if you're asking someone else you're both blocking yourself and create work for others.

**Comment by bidoubiwa** [comment]
Hey @bb, We are currently not adding new features to the mini-dashboard as per [the notice on the readme](https://github.com/meilisearch/mini-dashboard#mini-dashboard). I'm closing this for now. feel free to re-open it if the situation changes.
