### ISSUE TITLE
OSS image display bug

### ISSUE THREAD

**Issue by Avey777** [meilisearch/mini-dashboard#303]
When the first image is an OOS image link, Meilisearch will not display the OSS image normally; if the first image is in .png, .jpeg and other formats, the OSS image below can be displayed normally

![image](https://user-images.githubusercontent.com/35259040/181933847-a9178ee7-239e-43cc-a36e-79cd4467e2a8.png)

![image](https://user-images.githubusercontent.com/35259040/181933974-970d4850-9cbf-47de-bb6d-15869c673bda.png)

**Comment by curquiza** [comment]
Hello @Avey777 
I've moved the issue into the right repo so that @mdubus (the maintainer) can investigate it 😄 
Thanks for this report ❤️
