### ISSUE TITLE
Sorting and filtering in Search preview

### ISSUE THREAD

**Issue by gmourier** [meilisearch/mini-dashboard#305]
### Discussed in https://github.com/meilisearch/product/discussions/502

<div type='discussions-op-text'>

<sup>Originally posted by **bsurai** August  1, 2022</sup>
At the moment we are allowed to select an index and to enter a search text in the search preview. It would be convenient to be able to set in UI client:
- order, if an index has sortable attributes;
- filters, if an index has filterable attributes.</div>

**Comment by francoism90** [comment]
This would be great, any updates on this?

**Comment by bidoubiwa** [comment]
Hey @francoism90, this is not currently planned as it is does imply a lot of work. Nonetheless, you are definitely welcome to contribute and suggest an implementation of it

**Comment by vaibhav135** [comment]
@gmourier I would like to give it a shot? Is there any mockup for this?

**Comment by bidoubiwa** [comment]
We are currently not adding new features to the mini-dashboard as per [the notice on the readme](https://github.com/meilisearch/mini-dashboard#mini-dashboard). I'm closing this for now. feel free to re-open it if the situation changes.
