### ISSUE TITLE
deleteAllIndexes should also be added in test-api-key-required.cy file

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/mini-dashboard#334]
In the `e2e` tests runned by Cypress, most of the files delete all indexes to reset the environment before testing.
The file `test-api-key-required.cy.js` does not delete all indexes in a `before` function.

Unfortunately, a test from that files requires that there are no indexes currently on the Meilisearch instance.

https://github.com/meilisearch/mini-dashboard/blob/5683d1a4d688ede3f4e938951b9e0ba4cd54f03f/cypress/e2e/test-api-key-required.cy.js#L40

To tackle that issue, we need to add a `before` method in that test file, running `deleteAllIndexes`. 

See example here:

https://github.com/meilisearch/mini-dashboard/blob/5683d1a4d688ede3f4e938951b9e0ba4cd54f03f/cypress/e2e/test-no-api-key-required.cy.js#L5

**Comment by bidoubiwa** [comment]
Hey @developer-diganta ! Yes go ahaid :)

**Comment by developer-diganta** [comment]
If I am correct, I should add the before method after the beforeEach one?
