### ISSUE TITLE
Feature request: tasks inspector

### ISSUE THREAD

**Issue by joepio** [meilisearch/mini-dashboard#357]
I often want to see how my import is doing. I can write curl commands and all that, but it would be swell if the dashboard had a menu with a list of tasks and their information. Doesn't have to be too fancy.

**Comment by mdubus** [comment]
Hello @joepio 👋

First of all, thanks a lot for your suggestion!
As we already have something similar planned for our Saas product, we will focus on it instead of adding it inside the mini-dashboard. I'm leaving this issue open as it might interest other people 😃

Have a nice day! ☀️

**Comment by joepio** [comment]
Thanks for the response @mdubus!

If someone would open a PR, adding such a feature to the FOSS mini-dashboard, would you then accept that? Kind of awkward situation, as you'd have to balance two incentives: make the SAAS product attractive, and keep FOSS users happy!

**Comment by bidoubiwa** [comment]
We are currently not adding new features to the mini-dashboard as per [the notice on the readme](https://github.com/meilisearch/mini-dashboard#mini-dashboard). I'm closing this until the situation changes.
