### ISSUE TITLE
Values of `_geo` fields should be displayed as JSON in the dashboard

### ISSUE THREAD

**Issue by mmachatschek** [meilisearch/mini-dashboard#358]
**Description**
The `_geo` field is displayed as an empty field in the mini-dashboard because it contains a JSON string. This is very confusing for people that mainly access the meilisearch index via the mini-dashboard

**Expected behavior**
The JSON string should be outputed

**Current behavior**
The value of `_geo` is displayed as if it was empty

**Environment (please complete the following information):**
- Meilisearch version: v0.29.2
- Browser: Chrome
 
**Screenshots or Logs**
![image](https://user-images.githubusercontent.com/10237069/203785639-4e036532-edb2-4495-a009-0acd8141f854.png)

**Comment by mdubus** [comment]
Thanks a lot @mmachatschek for your bug report, I'll investigate it 🙏

**Comment by mdubus** [comment]
Hello @mmachatschek 👋 

This issue is solved with #363
A mini-dashboard release will be done today to fix it. It will be effective in the next Meilisearch release. 

Thanks again for the bug report 🙏 and have a nice day!

**Comment by ams-ryanolson** [comment]
I was JUST about to submit a bug report for this. Is this still a planned release or should I submit a new report?

**Comment by mmachatschek** [comment]
@ams-ryanolson the bugfix should be included in the meilisearch v1 release. the v0.30 release didn't include the fixed version of mini-dashboard

**Comment by bidoubiwa** [comment]
Hey @ams-ryanolson, @mmachatschek is right, it will be added in the v1 release of Meilisearch.
If you already need it, you can use the v1 rc of Meilisearch. v1 is not breaking v0.30.x.

https://github.com/meilisearch/meilisearch/releases/tag/v1.0.0-rc.0
