### ISSUE TITLE
Console error when you open the mini-dashboard

### ISSUE THREAD

**Issue by Kerollmops** [meilisearch/mini-dashboard#378]
When you run Meilisearch and you open the http://localhost:7700 URL the console log displays 4 errors. The instance of Meilisearch is completely fresh. It looks related to calls in the facets functions, maybe related to instant-meilisearch?

The logs are in the linked txt file.
[console-export.txt](https://github.com/meilisearch/mini-dashboard/files/10345597/console-export.txt)

**Environment:**
- Meilisearch version: main (v0.30.1)
- Browser: Firefox version 108.0.1

**Comment by mdubus** [comment]
Closing because this should be fixed with #381 

The fix should be visible in the next Meilisearch release :)
