### ISSUE TITLE
Console errors when using meilisearch with laravel sail

### ISSUE THREAD

**Issue by RealMrHex** [meilisearch/mini-dashboard#388]
**Describe the bug**
We created a new project and set up all the tools by default according to the documentation, but after entering the MeiliSearch panel, we encountered a lot of errors in the browser console.

**To Reproduce**
1. Create a new laravel-sail project.
2. Configure Scout and MeiliSearch PHP Client.
3. Import a Model.
4. Open meili-search dashboard at localhost:7700
5. See the Browser console

**Screenshots**
![image](https://user-images.githubusercontent.com/62525184/211945543-01429c08-e80a-40c9-b09f-567dd6ddabd0.png)
**Panel**

![image](https://user-images.githubusercontent.com/62525184/211945623-316f9ff6-1f7f-472c-8726-81fc129e5f88.png)
**Console**

**Meilisearch version:** v0.29.2

**Comment by mdubus** [comment]
Hello @RealMrHex !

Thanks a lot for your issue! This should be fixed by #381 which was merged and released on the mini-dashboard side. 
The fix should be visible in the next Meilisearch release :) 

Have a nice day!

**Comment by RealMrHex** [comment]
@mdubus Problem still not solved in mini-dashboard 30.0.5
![image](https://user-images.githubusercontent.com/62525184/214462894-10cde740-8350-4095-a3dd-d565e0be231d.png)

**Comment by bidoubiwa** [comment]
Hello! It's fixed in this [version of meilisearch](https://github.com/meilisearch/meilisearch/releases/tag/untagged-b12943fc69e4ae72f3ce). Its official release should happen in two weeks. Meanwhile the error will persist in v0.30.x of Meilisearch

**Comment by RealMrHex** [comment]
Any updates?

**Comment by bidoubiwa** [comment]
Which version of Meilisearch are you currently at? It should have been fixed in v1

**Comment by RealMrHex** [comment]
> Which version of Meilisearch are you currently at? It should have been fixed in v1

The latest version (1.1.x i think) and still not fixed :(

**Comment by bidoubiwa** [comment]
You're searching with no `index` selected. When trying to query, since there are no index it throws this error. I think it is expected. Can you select an index?

**Comment by RealMrHex** [comment]
@bidoubiwa Sure, ill check it tonight and update you ASAP.
Thanks for your attention ⚘️
