### ISSUE TITLE
Meilisearch Cloud - Document "Show More" button hides all attributes.

### ISSUE THREAD

**Issue by lundjrl** [meilisearch/mini-dashboard#413]
**Describe the bug**
When clicking on "Show More" for any document in our index, the entire document card goes blank (see screenshot).

**To Reproduce**
I'm not sure if this is happening to anyone else. But in our Cloud console, the steps are as follows.

1. Go to Cloud index and click preview. 
2. Click "Show More"
4. See error, card that was clicked is now blank (wasn't always like this).

**Expected behavior**
Clicking on "Show More" in Meilisearch cloud should show more attributes of an entry. 

**Screenshots**
![CleanShot 2023-02-28 at 08 38 21](https://user-images.githubusercontent.com/35306013/221871484-d866ea2d-b8bf-43a8-a7bc-672193bdeb11.png)

**Meilisearch version:**
v0.30.4

**Additional context**
Trying this on a Macbook pro with Chrome Version 110.0.5481.177 (Official Build) (x86_64)

**Comment by bidoubiwa** [comment]
Hey @lundjrl thanks for raising this bug! I tried locally on both v0.30 and v1 version of Meilisearch and I do not have the issue you have. 

Could you provide an example of a document in your index?
Could you look at your browser console (command + option + j) and provide the possible error that is thrown there?

**Comment by lundjrl** [comment]
@bidoubiwa Thanks for looking into this!
There's no error in the console itself. That's one of the first things I tried. I also looked in the network tab for anything weird there and nothing was out of the ordinary. I also tried on Firefox but that was the same.

Here's an example of what our documents look like:

> {
  "id": 3521,
  "name": "10 x 3\" SPAX T-20+ Flat Head PT 304 Stainless Steel - 3197000500750",
  "sku": "3197000500750",
  "description": "SPAX T-Star plus Flat Head, partial thread, stainless steel screws are the ideal multi-purpose decking and construction fastener. When premium corrosion resistance is desired, SPAX 304 stainless steel is the best exterior screw option. T-STAR plus drive provides superior bit engagement over Phillips and square drive screws.",
  "weight": 22.43,
  "width": 0,
  "depth": 9.5,
  "height": 7.9,
  "price": 0,
  "categories": [
    27,
    23
  ],
  "upc": "712216029798",
  "productType": "",
  "reviewsRatingSum": 0,
  "reviewsCount": 0,
  "isVisible": true,
  "relatedProducts": [
    -1
  ],
  "searchKeywords": "",
  "diameter": "#10",
  "length": "3\"",
  "driveType": "T-Star Plus",
  "headType": "Flat Head",
  "interiorExterior": "Exterior",
  "material": " 304 Stainless Steel",
  "origin": "Germany (DE)",
  "driveSize": "T-20+",
  "bitIncluded": true,
  "quantityPerPackage": "1500",
  "basePartNumber": "319700()",
  "packageType": "Bulk Pail",
  "color": "",
  "application": "Deck Dock / Marine Fence Pergola Shed",
  "threadLength": "1.600\"",
  "headSize": "0.390\"",
  "productDisplayName": "T-STAR PLUS FLAT HEAD 304 STAINLESS STEEL",
  "productShortDescription": "For use in cedar and redwood decking, and coastal environments.",
  "materialAndCoating": "304 stainless steel wire is code compliant for use in ground contact pressure treated and fire-retardant lumber, for exterior and coastal general construction applications (e.g. AWPA UC!-UC4B, UCFA, and UCFB).",
  "featuresAndSpecs": "• IRC / IBC Code Compliant DrJ TER No. 2010-02 Construction Screw Properties\n• Patented thread serrations require no pre-drilling and reduce driving torque to prolong the battery life of power tools\n• Ideal for use in cedar and redwood applications to prevent possible staining of the wood\n• 4CUT™ point prevents splitting of wood\n• T-STAR plus drive provides superior bit engagement",
  "typicalApplications": "• 2-by framing connections - coastal environment applications\n• Deck board finishing installation, especially cedar and redwood\n• Coastal decking or boardwalks\n• Exterior fencing\n• Outdoor furniture",
  "coating": "Stainless Steel"
}

**Comment by bidoubiwa** [comment]
Hey @lundjrl, I'm going on holliday but I'll take a look at this when I come back :)

**Comment by davelarkan** [comment]
>Do either of you know if there's a change in billing with the version update?

Hi @lundjrl there's no change in billing tied to the Meilisearch version. If you already have a project in Meilisearch cloud and you update that project to the latest version of Meilisearch your plan will remain unaffected.

If you choose to create a new project you can choose one of the plans outlined [on our pricing page](https://meilisearch.com/pricing).

**Comment by bidoubiwa** [comment]
It will be fixed with #419 and should be released in meilisearch v1.1
