### ISSUE TITLE
Display a banner mentioning the cloud product

### ISSUE THREAD

**Issue by gmourier** [meilisearch/mini-dashboard#441]
![Capture d’écran 2023-06-14 à 18 16 13](https://github.com/meilisearch/mini-dashboard/assets/3692335/29369f82-dab3-4dc7-bed2-54bca46ab0cd)

- The banner can be closed with the cross icon on the right. If it is closed, it should not reappear for the user again.
- It must be possible to deactivate it via a query parameter or a header, e.g `?banner=false`; It should not be displayed for users who open the mini-dashboard from the cloud interface.
- The link on "Meilisearch Cloud" is this [one](https://www.meilisearch.com/pricing?utm_campaign=oss&utm_source=integration&utm_medium=minidashboard).

@bidoubiwa I have a figma link at hand if needed

cc @mayasssh, @davelarkan, @brunoocasali

**Comment by davelarkan** [comment]
Thanks @gmourier 

The query param to hide the banner on the cloud should work fine for us. It's a little "fragile" but absolutely fine for a first iteration.

**Comment by mdubus** [comment]
Just thinking out loud, maybe we can use something like `document.referrer` to get the provenance URL and compare it with the Cloud URL 🤔
Don't know if that would work, some tests have to be made, but it could be a much "cleaner" solution than the query params one 😀
