### ISSUE TITLE
Add a `noindex` metatag 

### ISSUE THREAD

**Issue by gmourier** [meilisearch/mini-dashboard#448]
Search engines like Google should not list deployed mini-dashboard

**Comment by bidoubiwa** [comment]
Good idea! It should definitely be added

**Comment by manulpatel** [comment]
Hello @gmourier @gmourier! I am new to meilisearch and would liek to work on this issue. Could you give some hints to get started to develop the functionality?

**Comment by bidoubiwa** [comment]
Hey @manulpatel, there is a lot of information on line on how to add the `noindex` tag, if it's not enough please come back to us :)

To use Meilisearch and run the project in dev mode you can read the [contributing guide](https://github.com/meilisearch/mini-dashboard/blob/main/CONTRIBUTING.md), it should contain all the information needed.
