### ISSUE TITLE
Cloud promotion banner shows when you are on the cloud product

### ISSUE THREAD

**Issue by gillian-meilisearch** [meilisearch/mini-dashboard#466]
https://github.com/meilisearch/mini-dashboard/pull/442#issue-1759164968 introduced a banner to promote the cloud product.

This banner currently shows when you are on the cloud product. That is not necessary and should be removed from that context.

**Comment by gillian-meilisearch** [comment]
@bidoubiwa am I right to think this change is in mini-dashboard actually? or is it in cloud through a query param?

**Comment by bidoubiwa** [comment]
Hey @gillian-meilisearch! It should be something the cloud could disabled by providing the right query param. If the query param does not work, the issue comes from the mini-dashboard indeed.
