### ISSUE TITLE
Browse UI

### ISSUE THREAD

**Issue by crusht32** [meilisearch/mini-dashboard#467]
Implement a tool to send any requests to Meilisearch and receive the response in JSON:

https://roadmap.meilisearch.com/c/170-browse-ui

**Comment by bidoubiwa** [comment]
Hey @crusht32! Thanks for suggesting this enhancement. Unfortunately, we are currently not adding new features to the mini-dashboard as per [the notice on the readme](https://github.com/meilisearch/mini-dashboard#mini-dashboard). I'm closing this until the situation changes.
