### ISSUE TITLE
Development UI - Make it hybrid search

### ISSUE THREAD

**Issue by doreilly257** [meilisearch/mini-dashboard#500]
**Describe the bug**
The built-in development UI only does keyword search

**To Reproduce**
n/a

**Expected behavior**
Allow semantic search

**Screenshots**
n/a

**Meilisearch version:**
v1.8

**Additional context**
Maybe a slider for ratio is required.

**Comment by curquiza** [comment]
Hello @doreilly257 

The UI is related to the `mini-dashboard` repository. We provide a minimal UI and we don't plan to update it for the moment because of our bandwidth. Sorry :( 

However, anyone can fork the repo and improve it of course 👍
