### ISSUE TITLE
Fix vulnerability

### ISSUE THREAD

**Issue by curquiza** [meilisearch/mini-dashboard#527]
https://github.com/meilisearch/mini-dashboard/security/dependabot/49

<img width="963" alt="Capture d’écran 2024-06-26 à 16 41 27" src="https://github.com/meilisearch/mini-dashboard/assets/20380692/0c456db6-49f4-475b-a819-fe52abe06c78">

Due date: July 17th

**Comment by mdubus** [comment]
Done with https://github.com/meilisearch/mini-dashboard/pull/532
