### ISSUE TITLE
Display Cloud banner by default on self-host + revamp copy

### ISSUE THREAD

**Issue by gmourier** [meilisearch/mini-dashboard#563]
**Expected behavior**
- The Cloud banner is displayed by default when running a **self-hosted** instance (see attached screen)
    - It should not be displayed if the mini-dashboard is opened for a **cloud instance**; a query parameter exists for that `cloud_banner=false`
- The banner can be closed and not displayed again
- Banner's copy changes
    - Banner title: "Scale up with Meilisearch Cloud 🚀" 
    - Banner text: "Faster, smarter search—no maintenance needed. [Start free] with no commitment." (use current link)

**Current behavior**
- The banner does not show up by default when opening the mini-dashboard on a **self-hosted** instance

**Screenshots**
<img width="1640" alt="Screenshot 2024-11-21 at 11 31 04" src="https://github.com/user-attachments/assets/98ad5f3d-dc28-43e3-9fa1-47e012ff5185">

**Comment by mayasssh** [comment]
Slightly updated the copy (punctuation!)
