### ISSUE TITLE
Display MeiliSearch version in front-end

### ISSUE THREAD

**Issue by eskombro** [meilisearch/mini-dashboard#70]
**Is your feature request related to a problem? Please describe.**
When running a MeiliSearch instance with a front-end, I would like to see which version is running

**Describe the solution you'd like**
The Front-end could specify which MeiliSearch version is running, this makes it very easy and accessible, and avoid the user a few API calls or getting mixed with different versions

**Describe alternatives you've considered**
-

**Additional context**

- I am thinking of devops and deployment tools, where users request a MEiliSearch instance without necessarily being actively involved in the creation process. The only way to know the version in this case is doing an HTTP call to `/version` which requires from my POV too much actions/knowledge/involvment in the task for such a basic and important info
 
- Happy to do a PR if this idea is accepted

**Comment by curquiza** [comment]
I moved this issue to the mini-dashboard repo 🙂

**Comment by mdubus** [comment]
Thanks @curquiza  ! 
Indeed it is also missing in the current mini-dashboard, and it won't cost to add it. I'm gonna plan to add it 👌

**Comment by eskombro** [comment]
Thanks, @mdubus 🎉

**Comment by curquiza** [comment]
Can we have a new version of the mini-dashboard to integrate it in MeiliSearch? 😄
