### ISSUE TITLE
Code for current version of Web interface

### ISSUE THREAD

**Issue by julien-c** [meilisearch/mini-dashboard#91]
Hi,

Silly question, but where is the code for the current version of the Web interface? Haven't been able to find it.

Thanks!

**Comment by mdubus** [comment]
Hi ! 

I think you're looking for this : https://github.com/meilisearch/MeiliSearch/blob/release-v0.20.0/meilisearch-http/public/interface.html

With the v0.21, this file has been removed, and the old dashboard replaced by this one.

Don't hesitate if you have any other question 😀

**Comment by julien-c** [comment]
awesome, thank you:)
