### ISSUE TITLE
Highlight isn't working on the poster url

### ISSUE THREAD

**Issue by CaroFG** [meilisearch/mini-dashboard#93]
With the old dashboard and the movies dataset, on query: "psg", the following was returned

![Capture d’écran 2021-07-06 à 12 54 36](https://user-images.githubusercontent.com/48251481/124588953-b54b5200-de59-11eb-861c-a9b8d6e7e554.png)

As you can see, the poster URL is highlighted. With the new mini dashboard, it isn't so it makes it more difficult to know why we get that result:

![Capture d’écran 2021-07-06 à 12 47 40](https://user-images.githubusercontent.com/48251481/124589087-dca21f00-de59-11eb-8099-bf446e5bc224.png)

**Comment by mdubus** [comment]
Thanks a lot for reporting 🙏. PR is coming 🎉
